modLoader="kotlinforforge"
loaderVersion="[5,)"
license = "All Rights Reserved"

[[mods]]
modId = "tfmg_energy_connector"
version = "1.0.0"
displayName = "TFMG Energy Connector"
description = "Connects TFMG and FE"